# Generated by Django 4.1.2 on 2022-10-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_member_address_member_first_name_member_last_name_and_more'),
        ('profiles', '0002_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
