# Generated by Django 4.1.2 on 2022-10-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_renewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
