# Generated by Django 4.1.2 on 2022-10-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_membership_renewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership_renewed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
