# Generated by Django 4.1.2 on 2022-10-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_size',
            field=models.BooleanField(default=False),
        ),
    ]
