# Generated by Django 4.1.2 on 2022-10-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
    ]
