# Generated by Django 4.1.2 on 2022-10-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderitem_item_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=False, editable=False, max_length=32),
        ),
    ]
