# Generated by Django 4.1.2 on 2022-10-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='street_address2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
