# Generated by Django 4.1.2 on 2022-10-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address1',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
