# Generated by Django 4.1.2 on 2022-10-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_rename_street_address2_order_apartment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
    ]
