# Generated by Django 4.1.2 on 2022-10-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Amenites',
            },
        ),
        migrations.CreateModel(
            name='GymImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('alt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
                ('images', models.ImageField(upload_to='')),
                ('opening_hours_weekdays', models.TimeField()),
                ('opening_hours_weekends', models.TimeField()),
                ('closing_hours_weekdays', models.TimeField()),
                ('closing_hours_weekends', models.TimeField()),
                ('amenities', models.ManyToManyField(to='gym.amenity')),
            ],
        ),
    ]
