# Generated by Django 4.1.2 on 2022-10-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_membership_remove_gym_images_gymimage_gym_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='members',
            field=models.ManyToManyField(null=True, to='gym.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.membership'),
        ),
    ]
