# Generated by Django 4.1.2 on 2022-10-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_rename_price_membership_month_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='coordinates_lat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='coordinates_long',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
