# Generated by Django 4.1.2 on 2022-10-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_gym_coordinates_lat_gym_coordinates_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
