# Generated by Django 4.1.2 on 2022-10-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_member_address_member_first_name_member_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='month_price',
            new_name='monthly_price',
        ),
    ]
