# Generated by Django 4.1.2 on 2022-10-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_rename_month_price_membership_monthly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_renewed',
            field=models.DateTimeField(null=True),
        ),
    ]
