# Generated by Django 4.1.2 on 2022-10-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_user_profile'),
        ('gym', '0011_remove_member_member_remove_member_membership'),
        ('profiles', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='members',
            field=models.ManyToManyField(blank=True, to='profiles.userprofile'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
