# Generated by Django 4.1.2 on 2022-10-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_postcode_and_more'),
        ('gym', '0012_alter_gym_members_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='gym', to='profiles.userprofile'),
        ),
    ]
