# Generated by Django 4.1.2 on 2022-11-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_alter_gym_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='activation_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='cancelation_terms',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='membership',
            name='classes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='membership',
            name='days_notice_period',
            field=models.IntegerField(default=0, verbose_name='Notice Period (Days)'),
        ),
        migrations.AddField(
            model_name='membership',
            name='gym_access',
            field=models.CharField(default='', max_length=50),
        ),
    ]
