# Generated by Django 4.1.2 on 2022-11-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_gymsimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymSImage',
        ),
    ]
